print()
name = input("What is your name? ")
sur = input("What is your surname? ")
num = input("What is your phone number? ")
print()
#print('Your full name is' ,name ,sur)
#print('Your phone number is' ,num)
print("Your full name is " + str(name) + " " + str(sur) + ".")
print("Your phone number is " + str(num) + ".")
print()